#!/usr/bin/env node
/*
 * The 26 Club — encryption build step.
 *
 * Reads the editable content (src/content.json) and encrypts it into
 * enc/payload.js using AES-256-GCM with a key derived from the club password
 * via PBKDF2-SHA256. Only the encrypted blob is published — the password and
 * the plaintext content never leave your machine.
 *
 * Usage:
 *   CLUB_PASSWORD="your-password" node scripts/build.js
 *   node scripts/build.js "your-password"
 *
 * Matches the browser decrypt in js/gate.js (Web Crypto).
 */
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ITERATIONS = 250000;
const ROOT = path.resolve(__dirname, "..");

const password = process.env.CLUB_PASSWORD || process.argv[2];
if (!password) {
  console.error('Missing password. Run: CLUB_PASSWORD="..." node scripts/build.js');
  process.exit(1);
}

const contentPath = path.join(ROOT, "src", "content.json");
const raw = fs.readFileSync(contentPath, "utf8");
// Validate JSON and strip the _readme note from what we publish
const data = JSON.parse(raw);
delete data._readme;
const plaintext = Buffer.from(JSON.stringify(data), "utf8");

const salt = crypto.randomBytes(16);
const iv = crypto.randomBytes(12);
const key = crypto.pbkdf2Sync(password, salt, ITERATIONS, 32, "sha256");

const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);
const ct = Buffer.concat([cipher.update(plaintext), cipher.final()]);
const tag = cipher.getAuthTag();
// Web Crypto expects the auth tag appended to the ciphertext
const ctWithTag = Buffer.concat([ct, tag]);

const payload = {
  v: 1,
  iter: ITERATIONS,
  salt: salt.toString("base64"),
  iv: iv.toString("base64"),
  ct: ctWithTag.toString("base64")
};

const out =
  "/* AUTO-GENERATED by scripts/build.js — encrypted club content. Safe to publish. */\n" +
  "window.CLUB_PAYLOAD = " + JSON.stringify(payload) + ";\n";

const outPath = path.join(ROOT, "enc", "payload.js");
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, out);

console.log("Encrypted " + plaintext.length + " bytes of content -> enc/payload.js");
console.log("  posts:  " + (data.posts ? data.posts.length : 0));
console.log("  videos: " + (data.videos ? data.videos.length : 0));
